name: electron-build-pr

on:
  pull_request:
    branches:
    - master

jobs:
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64' 
    - name: Build on Ubuntu
      run: pip3 install -r requirements.txt
      run: npm install -g yarn
      run: npm install
      run: npm run start
      run: npm run build

  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64' 
    - name: Build on MacOS
      run: pip3 install -r requirements.txt
      run: npm install -g yarn
      run: npm install
      run: npm run start
      run: npm run build


  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64' 
    - name: Build on Windows
      run: pip install -r requirements.txt
      run: npm install -g yarn
      run: npm install
      run: npm run start
      run: npm run build

